export const subjects = [
  // "maths",
  // "language",
  // "science",
  // "history",
  // "coding",
  // "economics",
    "Analog and Digital Electronics",
    "Data Structure and Algorithm",
    "Computer Organisation",
    "Differential Calculus",
    "Economics for Engineers",
    "Discrete Mathematics",
    "Computer Architecture",
    "Automata Theory",
    "Environmental Science",
    "Biology",
    "Software Engineering",
    "Compiler Design",
    "Industrial Management",
    "Object Oriented Programming",
    "Artificial Intelligence",
    "Computer Graphics",
    "Theory of Computation",
    "Database Management System",
    "Computer Networks",
    "Image Processing",
    "Advance Algorithm",
    "Distributed Database Management System",
    "Data Warehousing and Mining",
    "Pattern Recognition",
    "Human Computer Interaction",
    "Quantum Computing",
    "Cloud Computing",
    "Machine Learning",
    "Digital Signal Processing",
    "Multi-agent Intelligent System",
    "Neural Networks and Deep Learning",
    "Soft Computing",
    "Cyber Security",
    "Signal and Networks",
    "Cryptography and Network Security",
    "Speech and Natural Language Processing",
    "Internet of Things",
    "Big Data Analysis",
    "Mobile Computing",
    "Robotics",
    "Soft Skills and Interpersonal Communication",
    "Ecommerce and ERP",
    "Micro-electronics and VLSI Design",
    "Economic Policie in India",
     "Programming Language C",
    "Programming Language Python",
    "Programming Language C++",
    "Programming Language Java",
];

export const subjectsColors = {
  // science: "#E5D0FF",
  // maths: "#FFDA6E",
  // language: "#BDE7FF",
  // coding: "#FFC8E4",
  // history: "#FFECC8",
  // economics: "#C8FFDF",
    "Analog and Digital Electronics": "#E5D0FF",
    "Data Structure and Algorithm": "#FFDA6E",
    "Computer Organisation": "#BDE7FF",
    "Differential Calculus": "#FFC8E4",
    "Economics for Engineers": "#FFECC8",
    "Discrete Mathematics": "#C8FFDF",
    "Computer Architecture": "#D0FFD0",
    "Automata Theory": "#FFD0D0",
    "Environmental Science": "#D0D0FF",
    "Biology": "#FFFFD0",
    "Software Engineering": "#E0FFE0",
    "Compiler Design": "#F0F0FF",
    "Industrial Management": "#FFE0F0",
    "Object Oriented Programming": "#E0F0FF",
    "Artificial Intelligence": "#FFE6CC",
    "Computer Graphics": "#CCFFE6",
    "Theory of Computation": "#E6CCFF",
    "Database Management System": "#CCEEFF",
    "Computer Networks": "#FFCCCC",
    "Image Processing": "#CCE0FF",
    "Advance Algorithm": "#FFCCEE",
    "Distributed Database Management System": "#CCFFCC",
    "Data Warehousing and Mining": "#FFCCAC",
    "Pattern Recognition": "#ACCFFC",
    "Human Computer Interaction": "#FFACC1",
    "Quantum Computing": "#AACCFF",
    "Cloud Computing": "#FFB2CC",
    "Machine Learning": "#B2CCFF",
    "Digital Signal Processing": "#CCFFB2",
    "Multi-agent Intelligent System": "#FFB2B2",
    "Neural Networks and Deep Learning": "#B2B2FF",
    "Soft Computing": "#B2FFB2",
    "Cyber Security": "#FFCCF2",
    "Signal and Networks": "#CCF2FF",
    "Cryptography and Network Security": "#F2FFCC",
    "Speech and Natural Language Processing": "#F2CCFF",
    "Internet of Things": "#CCF2CC",
    "Big Data Analysis": "#FFD9B3",
    "Mobile Computing": "#B3D9FF",
    "Robotics": "#D9B3FF",
    "Soft Skills and Interpersonal Communication": "#B3FFD9",
    "Ecommerce and ERP": "#D9FFB3",
    "Micro-electronics and VLSI Design": "#B3D9B3",
    "Economic Policie in India": "#D9B3D9",
    "Programming Language C": "#ADD8E6",
    "Programming Language Python": "#FFD700",
    "Programming Language C++": "#A0A0A0",
    "Programming Language Java": "#FF8C00",
};

export const voices = {
  male: { casual: "2BJW5coyhAzSr8STdHbE", formal: "c6SfcYrb2t09NHXiT80T" },
  female: { casual: "ZIlrSGI4jZqobxRKprJz", formal: "sarah" },
};

export const recentSessions = [
  {
    id: "1",
    subject: "Data Structure and Algorithm",
    name: "TechGuy",
    topic: "Linked List and its types",
    duration: 50,
    color: "#FFDA6E",
  },
  {
    id: "2",
    subject: "Discrete Mathematics",
    name: "TheNerd",
    topic: "Set Theory",
    duration: 30,
    color: "#C8FFDF",
  },
  {
    id: "3",
    subject: "Cyber Security",
    name: "Verba ",
    topic: "Introduction",
    duration: 20,
    color: "#FFCCF2",
  },
  {
    id: "4",
    subject: "Programming Language Python",
    name: "New Coder",
    topic: "Intro to If-Else Statements",
    duration: 25,
    color: "#E0F0FF",
  },
  {
    id: "5",
    subject: "Computer Networks",
    name: "Memo",
    topic: "OSI Model",
    duration: 60,
    color: "#FFCCCC",
  },
  {
    id: "6",
    subject: "Database Management System",
    name: "DataMonsters",
    topic: "Relational Model",
    duration: 40,
    color: "#CCEEFF",
  },
];
